In [1]:
import numpy as bi

In [2]:
a = bi.array([1,1,1,1])
a

array([1, 1, 1, 1])

In [3]:
a = bi.array([(1,1,1),(1,1,1)])
a

array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
a = bi.array([(1,1,1,1),(1,1,1,1),(1,1,1,1)])
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
a.shape

(3, 4)

In [6]:
a.size

12

In [7]:
a.ndim #number of dimension 

2

In [8]:
bi.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
bi.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
bi.zeros(4)

array([0., 0., 0., 0.])

In [11]:
bi.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
bi.zeros((4,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
bi.ones(4)

array([1., 1., 1., 1.])

In [14]:
bi.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
bi.ones((4,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
bi.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [17]:
bi.full((4,5),'😒')

array([['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒']], dtype='<U1')

In [18]:
bi.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
bi.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [20]:
bi.random.rand()

0.7354528828150655

In [21]:
bi.random.rand(4)

array([0.3659205 , 0.82914907, 0.95259151, 0.76453963])

In [22]:
bi.random.rand(3,4) *10

array([[7.75077953, 7.60027089, 9.37053467, 0.66224919],
       [8.90603393, 0.72671384, 0.51892056, 7.19961107],
       [9.43978498, 4.02732932, 7.63291998, 1.99281729]])

In [23]:
bi.random.randint(1,40)

25

In [24]:
bi.random.randint(1,40,(4,5))

array([[ 4, 11, 28, 30, 15],
       [21, 35, 15, 21, 20],
       [21, 33, 32, 21, 16],
       [15, 39, 24,  8,  1]], dtype=int32)

In [25]:
a = bi.array([13,34,56,34,12])
b = bi.array([1,2,3,4,5])

print(a)
print(b)

[13 34 56 34 12]
[1 2 3 4 5]


In [26]:

bi.add(a,b)

array([14, 36, 59, 38, 17])

In [27]:
bi.subtract(a,b)

array([12, 32, 53, 30,  7])

In [28]:
bi.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [29]:
bi.log(a)

array([2.56494936, 3.52636052, 4.02535169, 3.52636052, 2.48490665])

In [30]:
bi.sqrt(a)

array([3.60555128, 5.83095189, 7.48331477, 5.83095189, 3.46410162])

In [31]:
bi.repeat(a,2)

array([13, 13, 34, 34, 56, 56, 34, 34, 12, 12])

In [32]:
bi.where(a==34)

(array([1, 3]),)

In [38]:
b = bi.random.randint(1,40,(5,5))
b

array([[39,  6, 19, 39, 28],
       [11, 36, 10, 34, 11],
       [18, 16, 11, 37, 31],
       [29, 12, 35, 12, 31],
       [17,  5, 39, 16, 17]], dtype=int32)

In [39]:
b[:3:2,2:4:1]

array([[19, 39],
       [11, 37]], dtype=int32)